### ISSUE TITLE
annotation step seems to take a long time

### ISSUE THREAD

**Issue by linminhtoo** [genepi/nf-gwas#101]
hi all,

i have an annotation file that is a .tsv.gz with 1 million rows (variants), and I see the annotation step after REGENIE steps 1 & 2 seems to take a long time (NF_GWAS:SINGLE_VARIANT_TESTS:ANNOTATION:ANNOTATE_RESULTS). 

currently it seems like for 1 million rows it takes 44 minutes on 8 CPUs & 4 GB. Which seems a bit long relative to the actual steps 1 & 2 of REGENIE. I went to see the Java source code & it seems a bit inefficient doing row-by-row sequential processing with single thread. Do you think this step can be multi-threaded or sped up in any way?  
Thanks

**Comment by seppinho** [comment]
* Did you set the chunking parameters? Annotation is executed for each regenie chunk, so it is executed in parallel. In case you didnt specifiy chunking, annotation is executed on a chromosome level.  https://genepi.github.io/nf-gwas/params/optional_params.html#chunking
* Did you try to set the path to the rsID file? If not, the file is downloaded for every exection: https://genepi.github.io/nf-gwas/params/optional_params.html#annotation-and-gwas-report

Hope this helps.
Best
Sebastian

**Comment by seppinho** [comment]
Closing this now. Feel free to reopen.
