### ISSUE TITLE
Gene level test option

### ISSUE THREAD

**Issue by g-antonello** [genepi/nf-gwas#39]
Dear developers,
Regenie 3 allows for gene-level testing (https://rgcgithub.github.io/regenie/options/#gene-based-testing), but it requires to play with the step 2 configuration script. Is it already possible to make such an analysis with nextflow?

If not, what do you suggest? I also attach the example steps configurationsl, highlighting in red the differences between the  two analysis parameters.

All the best, 
Giacomo

![regenieExampleSettings](https://user-images.githubusercontent.com/57659689/169854354-00401fc7-7ab7-453a-be97-5d9c03662e53.PNG)

**Comment by seppinho** [comment]
Any chance you can provide test data (set-list, anno-file, etc) ? I'm happy to implement this!
Best.
Sebastian

**Comment by filosi** [comment]
Hi Seb, I started working on the integration of the gene level analysis, you can have a look at the progresses in the for of you repo in my github: branch develop [https://github.com/filosi/nf-gwas/tree/develop](https://github.com/filosi/nf-gwas/tree/develop)
You can find some test data in the `tests/input/gene_level` directory

**Comment by seppinho** [comment]
The branch has now been merged. Thanks for all feedback and suggestions!
