### ISSUE TITLE
Issues with empty files on cloud

### ISSUE THREAD

**Issue by abhi18av** [genepi/nf-gwas#47]
Hi team, 

Since we're already evaluating use of bundled JARs in the container, I went ahead and tested with the next steps (once we're past the jar issues).

The problems here seems to be the use of empty files, for example `NO_COV_LOG` here https://github.com/genepi/nf-gwas/blob/6367cc80cc93d867b4da440ccb97b15afc9006a9/workflows/nf_gwas.nf#L46 

This works fine on real filesystems, however as cloud also provides the option to run a pipeline using a blob storage as a backend (Azure Blob container or AWS S3) , this expectation fails.

I'm currently working on a separate internal branch to test this and once that's done I'll add here for a review.

**UPDATE**: I've merged that code within https://github.com/genepi/nf-gwas/pull/46

**Comment by lukfor** [comment]
Great! Thanks for your help 🙏
