### ISSUE TITLE
Error while running the pipeline on a test dataset

### ISSUE THREAD

**Issue by nafizh** [genepi/nf-gwas#56]
If I run the command 

nextflow run genepi/nf-gwas -r v0.5.0 -profile test, docker

the following error is occuring-

![Screenshot from 2022-10-21 11-42-27](https://user-images.githubusercontent.com/9099617/197235592-9f43cf3a-9d91-4d3f-992a-7255a583c63d.png)

I couldn't find this RegenieValidateInput.jar file in the github repo.
Could you please let me know what am I missing here?

**Comment by seppinho** [comment]
You had a space between test and docker.
Correct command is:
`nextflow run genepi/nf-gwas -r v0.5.0 -profile test,docker`

**Comment by nafizh** [comment]
Thanks, that solved the issue.
A better error message might be helpful.
Thanks for your work.
