### ISSUE TITLE
problem with rsID file download

### ISSUE THREAD

**Issue by samuelecancellieri** [genepi/nf-gwas#69]
hi, I'm trying to use the next low pipeline version 0.6.3 and when the pipe tries to download the rsID file, I get this error.

Process `NF_GWAS:DOWNLOAD_RSIDS` is unable to find [UnixPath]: `/shares/CIBIO-Storage/NB/scratch/sfari_new/WGS123_complete_run_cov-pheno/c4/06e662ebb16c20061e9616ad88159b/rsids-v154-null.index.gz` (pattern: `rsids-v154-null.index.gz`)
Jun-14 10:34:12.791 [Task monitor] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=NF_GWAS:DOWNLOAD_RSIDS; work-dir=/shares/CIBIO-Storage/NB/scratch/sfari_new/WGS123_complete_run_cov-pheno/c4/06e662ebb16c20061e9616ad88159b
  error [nextflow.exception.MissingFileException]: Missing output file(s) `rsids-v154-null.index.gz` expected by process `NF_GWAS:DOWNLOAD_RSIDS`
Jun-14 10:34:12.820 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'NF_GWAS:DOWNLOAD_RSIDS'

Caused by:
  Missing output file(s) `rsids-v154-null.index.gz` expected by process `NF_GWAS:DOWNLOAD_RSIDS`

I'm attaching the config file for reference and the entire log.
[.nextflow.log.7.txt](https://github.com/genepi/nf-gwas/files/11756137/default.nextflow.log.7.txt)
[gwas_conf.conf.txt](https://github.com/genepi/nf-gwas/files/11756123/gwas_conf.conf.txt)

Thanks a lot.

**Comment by filosi** [comment]
Hi Samuele,
I downloaded a copy of the rsid file from `https://resources.pheweb.org/` and use a local copy without having to download every time.
Then set the parameter `rsids_filename=<path_to_my_rsid_file>`.
This is not solving the issue in general, but it will work and speed-up the workflow if you have to run multiple GWAS.

**Comment by seppinho** [comment]
Thanks. The reported issue should be fixed with the new version (v0.6.4). Thanks @filosi for pointing to the alternative.

**Comment by samuelecancellieri** [comment]
Thanks, I will test ASAP.

Best,
