### ISSUE TITLE
Gene-level analysis

### ISSUE THREAD

**Issue by filosi** [genepi/nf-gwas#70]
An error is thrown when using plink set files divided by chromosome on gene-level analysis.
In particular for:
`genotype_association=<mydir>/chr*.{bim,bed,fam}`
Error on `REGENIE_STEP2_GENE_TESTS`:
`chr1.bed Not Found`

When running with: 
`genotype_association=<mydir>/chr1.{bim,bed,fam}`

Everything goes fine.

**Comment by seppinho** [comment]
This has been fixed by supporting VCF and BGEN for gene-based testing in #92
