### ISSUE TITLE
Issue with Gene level analysis on MERGE_RESULTS

### ISSUE THREAD

**Issue by filosi** [genepi/nf-gwas#72]
If a setlist contains a key containing "CHROM" string the header line of the summary stat will contain multiple lines and the tabix fail creating the indexing.

**Comment by seppinho** [comment]
Thanks for reporting. We changed the merge logic and used a csvtk for the merging logic. The pull https://github.com/genepi/nf-gwas/pull/77 will also solve this issue, I will therefore close your other pull-request.

**Comment by lukfor** [comment]
Thanks guys! Is fixed [v0.7.2](https://github.com/genepi/nf-gwas/releases/tag/v0.7.2)
